plugins {
    id 'java'
    id "org.springframework.boot" version "${SPRING_BOOT_VERSION}" apply false
    id "io.spring.dependency-management" version "${SPRING_BOOT_DEPENDENCY_MANAGEMENT_VERSION}" apply false
    id 'org.jetbrains.kotlin.jvm' version "${KOTLIN_VERSION}" apply false
    id 'org.jetbrains.kotlin.plugin.spring' version "${KOTLIN_VERSION}" apply false
}

allprojects {
    group = "com.resustack"
    version = "0.0.1-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: "java"
    apply plugin: "io.spring.dependency-management"
    apply plugin: "org.jetbrains.kotlin.jvm"
    apply plugin: "org.jetbrains.kotlin.plugin.spring"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(Integer.parseInt(JAVA_VERSION))
        }
    }

    kotlin {
        jvmToolchain(Integer.parseInt(JAVA_VERSION))
        compilerOptions {
            freeCompilerArgs.addAll '-Xjsr305=strict', '-Xannotation-default-target=param-property'
        }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${SPRING_BOOT_VERSION}"
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    dependencies {
        // Kotlin
        implementation 'org.jetbrains.kotlin:kotlin-reflect'

        // Lombok
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'

        // Test
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.register("prepareKotlinBuildScriptModel"){}
}
