# SpringBoot
SPRING_BOOT_VERSION=4.0.0
SPRING_BOOT_DEPENDENCY_MANAGEMENT_VERSION=1.1.7

# Language
JAVA_VERSION=21
KOTLIN_VERSION=2.2.21

# Liquibase
LIQUIBASE_VERSION=5.0.1
LIQUIBASE_MONGODB_VERSION=5.0.1

# Swagger
SWAGGER_UI_VERSION=3.0.0

# Mockito-Kotlin
MOCKITO_KOTLIN_VERSION=6.1.0

# JJWT
JJWT_VERSION=0.12.6
