plugins {
    id "org.springframework.boot"
    id "io.spring.dependency-management"
    id "org.jetbrains.kotlin.jvm"
    id "org.jetbrains.kotlin.plugin.spring"
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}

dependencies {
    // Internal modules
    implementation(project(':resustack-common')) {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-data-jpa'
    }
    implementation 'jakarta.persistence:jakarta.persistence-api'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.aspectj:aspectjweaver'
    implementation 'org.springframework:spring-aop'
    implementation 'tools.jackson.module:jackson-module-kotlin'

    // MongoDB
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-mongodb'

    // liquibase
    implementation "org.liquibase:liquibase-core:${LIQUIBASE_VERSION}"
    implementation "org.liquibase.ext:liquibase-mongodb:${LIQUIBASE_MONGODB_VERSION}"

    // Swagger UI
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${SWAGGER_UI_VERSION}"

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-data-mongodb-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-mongodb-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'

    // Mockito
    testImplementation 'org.mockito:mockito-core'
    testImplementation "org.mockito.kotlin:mockito-kotlin:${MOCKITO_KOTLIN_VERSION}"

    // Testcontainers
    testImplementation "org.testcontainers:testcontainers:${TESTCONTAINERS_VERSION}"
    testImplementation "org.testcontainers:junit-jupiter:${TESTCONTAINERS_VERSION}"
    testImplementation "org.testcontainers:mongodb:${TESTCONTAINERS_VERSION}"
}
