services:
  mongodb:
    image: mongo:8.0
    container_name: resustack-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: resustack
      MONGO_INITDB_ROOT_PASSWORD: resustack
      MONGO_INITDB_DATABASE: resustack
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  postgres:
    container_name: resustack-postgresql
    environment:
      POSTGRES_USER: resustack
      POSTGRES_PASSWORD: resustack
      POSTGRES_DB: resustack
    image: postgres:16
    ports:
      - "5435:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U resustack -d resustack" ]
      interval: 30s
      timeout: 1s
      retries: 5

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  pg-data:
    driver: local
