services:
  mongodb:
    image: mongo:8.0
    container_name: resustack-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: resustack
      MONGO_INITDB_ROOT_PASSWORD: resustack
      MONGO_INITDB_DATABASE: resustack
    entrypoint:
      - bash
      - -c
      - |
        echo "bXlzZWNyZXRrZXkxMjM0NTY=" > /data/configdb/keyfile
        chmod 400 /data/configdb/keyfile
        chown 999:999 /data/configdb/keyfile
        exec docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/configdb/keyfile --bind_ip_all
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: [
        "CMD-SHELL",
        "mongosh --quiet -u resustack -p resustack --authenticationDatabase admin --eval 
        \"try { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }).ok } 
        catch (_) { rs.status().ok }\" | grep -q 1"
      ]
      interval: 10s
      start_period: 30s

  postgres:
    container_name: resustack-postgresql
    environment:
      POSTGRES_USER: resustack
      POSTGRES_PASSWORD: resustack
      POSTGRES_DB: resustack
    image: postgres:16
    ports:
      - "5435:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U resustack -d resustack" ]
      interval: 30s
      timeout: 1s
      retries: 5

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  pg-data:
    driver: local
