version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: resustack-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: resustack
      MONGO_INITDB_ROOT_PASSWORD: resustack
      MONGO_INITDB_DATABASE: resustack
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
